### ISSUE TITLE
No Digging Zombies

### ISSUE THREAD

**Issue by stevojhall** [stallionsden/stallionsmodlets#1]
I'm looking at the files for No Digging zombies and trying to work out how this was achieved so i can add this to the extra zombies from darkness falls and ravenhearst but cannot seem to workout what has changed and because it is set up as a modlet compare does not work.

i am not planning on releasing as a mod just want any changes from ravenhearst and darkness falls to take priority except digging and as the changes are to base files your files override those files.

**Comment by stallionsden** [comment]
hi stevojhall

in the blocks.xml  i added all the terrain types and made them 0 damage to
each z.

sorry it took a while to reply have been busy.

Stallionsden

**Comment by stevojhall** [comment]
Thank you for that, thought there was something in the entityclasses.xml that i was missing lol.

I will check out adding the terrain types.
